name: tamka
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core:
  google_sign_in:
  shared_preferences:
  random_string:
  font_awesome_flutter:
  cloud_firestore:
  lottie:
  sizer:
  cupertino_icons: ^1.0.0
  flutter_speed_dial: ^5.0.0+1
  carousel_slider: ^4.0.0
  swipe_to: ^1.0.2
  readmore: ^2.1.0
  url_launcher:
  timeago:
  icons_launcher: ^1.1.7
  firebase_storage: ^10.2.12
  youtube_player_flutter: ^8.0.0
  flutter_chat_bubble:
  flutter_launcher_icons: ^0.9.2
    # store file on device
  path_provider: ^2.0.1


flutter_icons:
  image_path: 'assets/icon/logo.png'
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/logo.png